# Site settings
title: Akilesh Lakshminarayanan
email: akilesh1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"

  I write code on R, Python and C++. Occational sports data nerd.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://akileshlaksh.com" # the base hostname & protocol for your site
twitter_username: leshtalks
github_username:  akilesh1995
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
